# Generated by Django 2.2.1 on 2019-06-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_timelines_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelines',
            name='heading',
        ),
    ]
