# Generated by Django 2.2.1 on 2019-06-05 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_timelines_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='icon_urls',
            field=models.URLField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='carreer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timelines',
            name='years',
            field=models.CharField(max_length=100),
        ),
    ]
