# Generated by Django 2.2.1 on 2019-06-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190605_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='icon_urls',
        ),
        migrations.AddField(
            model_name='team',
            name='icon_face',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='icon_gmail',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='icon_insta',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='icon_twi',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
