# Generated by Django 2.2.1 on 2019-06-05 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190605_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='icon_face',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='icon_gmail',
            new_name='gmail',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='icon_insta',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='icon_twi',
            new_name='twitter',
        ),
    ]
