# Generated by Django 2.2.1 on 2019-06-09 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190609_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
