# Generated by Django 2.2.3 on 2019-08-08 17:05

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_contactinfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='business_email',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='email_avail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='flexibility',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
