# Generated by Django 2.2.1 on 2019-06-06 23:36

from django.db import migrations, models
import fontawesome.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('job', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
