# Generated by Django 2.2.1 on 2019-06-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('title', models.CharField(max_length=100)),
                ('brief_info', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
                ('site', models.URLField()),
                ('date', models.DateField()),
            ],
        ),
    ]
