# Generated by Django 2.2.1 on 2019-06-06 02:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
