# Generated by Django 2.2.1 on 2019-06-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='brief_info',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='site',
            field=models.URLField(blank=True),
        ),
    ]
